### ISSUE TITLE
Set up Kanban board

### ISSUE THREAD

**Issue by AlejandraKeber** [MahdiSohaily/JS-capstone#21]
## Hello code reviewer 👋 

We created this issue in order to have a review for our Kanban board: tasks, estimation time, and the assignee for each task.
We are a group of two:  

- Mahdi Rezaei- Student A
- Alejandra Keber - Student B

The link to our project is the following: https://github.com/MahdiSohaily/JS-capston/projects/2

## Thank you and have a great day! 👍

**Comment by thecodechaser** [comment]
## STATUS: APPROVED 🟢

## Hi @AlejandraKeber, and @MahdiSohaily👋, 

Your project is complete!  There is nothing else to say other than... it's time to close it :shipit: 
Congratulations! 🎉 

<img src="https://media3.giphy.com/media/g9582DNuQppxC/giphy-downsized-medium.gif"/>

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
